version: "3"
volumes: 
   models_zip:
    
services:
  mongo:
    image: mongo:4.0
    environment: 
      MONGO_INITDB_ROOT_USERNAME: dna2bpmuser
      #change the password below and keep it for installation
      MONGO_INITDB_ROOT_PASSWORD: "kukekakuke50"
    ports:
      - "27017:27017"

  web:
    image: juanitomint/dna2bpm:latest
    ports:
      - "80:80"

    volumes:
      - models_zip:/var/www/html/application/modules/bpm/assets/files/images/zip


# uncomment  the block below to enable an itegrated c9 editor on port 9022
  # editor:
  #   image: juanitomint/c9collab:php7
  #   volumes:
  #       - ./:/workspace
  #       - ./ssh/:/root/.ssh
  #   ports:
  #     - "9022:80"
